object Form2: TForm2
  Left = 495
  Top = 134
  Width = 746
  Height = 558
  BorderIcons = [biSystemMenu, biMaximize]
  Caption = 'Statistics'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -12
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsStayOnTop
  KeyPreview = True
  OldCreateOrder = False
  OnKeyDown = FormKeyDown
  PixelsPerInch = 106
  TextHeight = 13
  object Chart1: TChart
    Left = 0
    Top = 0
    Width = 738
    Height = 529
    AllowPanning = pmNone
    AllowZoom = False
    BackWall.Brush.Color = clWhite
    BackWall.Brush.Style = bsClear
    BackWall.Pen.Visible = False
    Foot.Visible = False
    Gradient.Direction = gdRightLeft
    Gradient.EndColor = 16553825
    Gradient.Visible = True
    Title.Font.Charset = DEFAULT_CHARSET
    Title.Font.Color = clBlue
    Title.Font.Height = -15
    Title.Font.Name = 'Arial'
    Title.Font.Style = []
    Title.Text.Strings = (
      'Running Time Percentages')
    AxisVisible = False
    BottomAxis.EndPosition = 99
    ClipPoints = False
    Frame.Visible = False
    LeftAxis.Labels = False
    LeftAxis.Title.Caption = 'Applications'
    Legend.Visible = False
    View3D = False
    View3DOptions.Elevation = 315
    View3DOptions.Orthogonal = False
    View3DOptions.Perspective = 0
    View3DOptions.Rotation = 360
    View3DWalls = False
    Align = alClient
    TabOrder = 0
    AutoSize = True
    object Series1: TPieSeries
      Marks.ArrowLength = 5
      Marks.Style = smsLabelPercent
      Marks.Visible = True
      SeriesColor = clRed
      ShowInLegend = False
      OtherSlice.Text = 'Other'
      PieValues.DateTime = False
      PieValues.Name = 'Pie'
      PieValues.Multiplier = 1
      PieValues.Order = loDescending
    end
    object Series2: THorizBarSeries
      Active = False
      ColorEachPoint = True
      Marks.ArrowLength = 20
      Marks.Visible = True
      SeriesColor = clGreen
      XValues.DateTime = False
      XValues.Name = 'Bar'
      XValues.Multiplier = 1
      XValues.Order = loNone
      YValues.DateTime = False
      YValues.Name = 'Y'
      YValues.Multiplier = 1
      YValues.Order = loNone
    end
  end
end
